apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: frontend-ns
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: frontend
          image: asia-northeast3-docker.pkg.dev/bubbly-enigma-423300-m7/gar-io/travellog-frontend:latest
          ports:
            - containerPort: 3000
