# Generated by Django 4.2 on 2024-04-28 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('TravelID', models.AutoField(primary_key=True, serialize=False)),
                ('City', models.CharField(max_length=50)),
                ('Money', models.IntegerField()),
                ('Tag', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=50)),
                ('Journal', models.CharField(max_length=500)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='travel.userdata')),
            ],
        ),
    ]
